---
- name: Repository Configuration
  hosts: webservers
  tasks:
    - name: Ensure Example Repo exists
      yum_repository:
        name: download.vscodium.com
        description: gitlab.com_paulcarroty_vscodium_rep 
        file: vscodium
        baseurl: https://download.vscodium.com/rpms/
        gpgcheck: yes

    - name: Ensure Repo RPM key is Installed
      rpm_key:
        key: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg
        state: present

    - name: Install Example motd package
      yum:
        name: codium
        state: present


